name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build apps
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Deploy backend to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          npm install -g heroku
          heroku auth:token --token=$HEROKU_API_KEY
          git remote add heroku https://git.heroku.com/${HEROKU_APP_NAME}.git
          git push heroku master

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist/apps/ticket-swap-app --prod

